### ISSUE TITLE
Update readme for Chef 12.1

### ISSUE THREAD

**Issue by coderanger** [thommay/chef-rewind#3] opened 2015-03-31 07:52 UTC
With the `compile_time` changes, the readme needs an update.

**Comment by scalp42** [comment] 2015-06-14 03:59
Could you be more specific by any chance @coderanger so maybe I can help please?

Thanks in advance!

**Comment by coderanger** [comment] 2015-06-14 04:04
In 12.1, Chef shows a warning if `compile_time` is left set to `true`. Something more like:

```ruby
chef_gem 'chef-rewind' do
  action :nothing
end.run_action(:install)
```

Seems to be the remaining way to install a gem at compile time without a warning. Alternatively this gem could be scrapped and the whole thing could be rebuilt as a cookbook instead, which gets around any compile/converge-time issues.

**Comment by aaron-lane** [comment] 2015-10-19 18:23
My understanding of the [behavior introduced in 12.1](https://www.chef.io/blog/2015/03/03/chef-12-1-0-released/) is that the warning will only be generated if the `compile_time` attribute is not explicitly set. 

This approach is more idiomatic and should not generate a warning:
```ruby
chef_gem 'chef-rewind' do
  compile_time true
end
```

**Comment by Rud5G** [comment] 2015-12-04 15:18
Does chef-rewind need to be installed at compile-time?

**Comment by aaron-lane** [comment] 2015-12-07 16:27
It needs to be installed at compile time so that errors aren't raised when the chef-client compiles the `rewind` and `unwind` resources.

**Comment by lamont-granquist** [comment] 2015-12-16 21:04
This shouldn't be a gem, it should just be a library file...

**Comment by scalp42** [comment] 2015-12-16 23:14
This gem is vital literally for wrapper cookbooks.

**Comment by lamont-granquist** [comment] 2015-12-16 23:36
Two things:

- its this cookbook that you need, not the gem implementation under it and the need to chef_gem which is a huge kludge.

- you also literally don't need it to write wrapper cookbooks:

```
r = resources(template: "#{node['redis']['conf_dir']}/redis.conf")
r.cookbook(cookbook_name)
```

does the same thing as:

```
rewind "template[#{node['redis']['conf_dir']}/redis.conf}]" do
  cookbook(cookbook_name)
end
```

chef-rewind functionality is literally built right in to chef.

**Comment by scalp42** [comment] 2015-12-17 03:35
How would you delete a resource @lamont-granquist  ?

The issue is that the DSL is great and easy for newcomers.

I'm curious why everybody's been moving to libraries left/right lately actually.

**Comment by scalp42** [comment] 2015-12-17 03:40
On a side note I noticed something broke with newer versions of Chef.

Imagine the scenario:

You use a `ruby_block` `B` with action `nothing` and have a resource `A` notifies `run` to the `ruby_block`.

You have a last resource `C` that `subscribe` to the `ruby_block` (common pattern).

You could `rewind` the resource `C` and have notifications working but not anymore. Not sure if it's 12.5.4 or `compat_resource`.

**Comment by lamont-granquist** [comment] 2015-12-17 18:16
unwind is this simple:

https://github.com/thommay/chef-rewind/blob/master/lib/chef/rewind.rb#L42-L44

one-liner without chef-rewind:

```
run_context.resource_collection.delete_resource "template[whatever]"
```

everyone is moving to libraries files for their resources and providers for reasons that i don't understand.  i would advise using the resources DSL, particularly the new one until you hit a point where you can't.  i've been told by john keiser that the new DSL can handle inheriting from base classes and doing 1:N resources-to-provider models so there should be no reason to use libraries for those.

for this, however, you're injecting methods into the DSL.  these should just be normal chef libraries.  then chef itself would load up the library, with no reason to do a chef_gem, and no reason to publish a gem.  you're using a gem in order to ship a single ruby library file around when chef-client already has library files you can distribute with cookbooks.  it needlessly involves rubygems.

i think chef-rewind was following the chef-sugar pattern just to follow that pattern, but chef-sugar has a reason for being a gem, and we include chef-sugar as a dep of omnibus and mix it in with the DSL there outside of chef-client.  nobody does that with chef-rewind because its necessarily tightly coupled to the chef-client resource collection.

**Comment by lamont-granquist** [comment] 2015-12-17 18:22
oh yeah, if you can cut down the bugginess down to an isolate chef-apply recipe (or if its a compat_resource bug then use chef-client -z and make a trivial cookbook that has compat_resource as a dep) you should just cut a bug (against chef-client or compat_resource as appropriate).  i haven't heard about that one and it sounds very odd.  offhand i can't imagine how that is going wrong (all you do with rewind is look up and grab a reference to the object on the resource collection and then poke it with normal DSL methods, so having the subscribes disappear should not happen or we'd see it in normal chef code as well).  my guess is that if you cut your example down you'll find it works and then as you try to figure out the difference between the two you'll see that your example wasn't that simple and something else is going on and it has something to do with your code--but of course i've seen stranger bugs that were real bugs, so if you cut it down and it still fails, file a ticket...

**Comment by lamont-granquist** [comment] 2016-10-07 16:25
@thommay should close this, its covered much better now under https://coderanger.net/rewind/ with less of me just being grouchy

**Closed** 2016-10-07 16:29 UTC
